### ISSUE TITLE
Very nice! What about the other way around?

### ISSUE THREAD

**Issue by eduarddrenth** [jfree/fxgraphics2d#3]
I would like to be able to draw javafx nodes to a Graphics2D so I can draw these in frameworks that use Graphics2D. Sofar I do not have a solution, perhaps overriding JFXPanel#paintComponent is a good starting point.

**Comment by eduarddrenth** [comment]
Works, only thing is I have to create a JFrame and set visible to true to trigger rendering. Also I have to instantiate a JFXPanel before instantiating JavaFX Chart nodes to get rid of "Toolkit not initialized".

Not realy flexible, but I don't see a better way for now

**Comment by jfree** [comment]
There is a feature request for using a graphics layer in JavaFX along the lines of the way Swing uses Graphics2D.  It's an excellent request, but has been given a very very low priority...I don't think it will be implemented.

https://bugs.openjdk.java.net/browse/JDK-8091853

**Comment by eduarddrenth** [comment]
Too bad, created https://github.com/eduarddrenth/JavaFXSceneToGraphics2D,
perhaps usefull for some
