### ISSUE TITLE
Incorrect range adding single series to empty XYSeriesCollection in XYPlot in CombinedDomainXYPlot

### ISSUE THREAD

**Issue by DuaneTiemann** [jfree/fxgraphics2d#4]
This doesn't happen if the XYPlot is added to the CombinedDomainXYPlot after it contains a series.

Adding a second series results in a correct image.

Duane Tiemann
jfreechart-1.0.19.jar as distributed
Code provided in OneSeriesProblem.txt because .java is not allowed.

[OneSeriesProblem.txt](https://github.com/jfree/fxgraphics2d/files/478786/OneSeriesProblem.txt)
![singleseries](https://cloud.githubusercontent.com/assets/16293646/18616863/a8ac1d64-7d91-11e6-8120-ac4d29c9d742.png)
![twoseries](https://cloud.githubusercontent.com/assets/16293646/18616864/ac1aabf0-7d91-11e6-97ef-f9d7a2fa7560.png)

Code provided in OneSeriesProblem.txt since .java is not allowed.

**Comment by jfree** [comment]
This should be in the JFreeChart tracker, not here (FXGraphics2D).  I will close this one, already opened an issue at the JFreeChart page:

https://github.com/jfree/jfreechart/issues/69
