### ISSUE TITLE
Demo classes no longer runnable since not included in any jar files

### ISSUE THREAD

**Issue by javadba** [jfree/fxgraphics2d#5]
Directly on the README.md we have instructions to run demo program:

   java -cp fxgraphics2d-1.5-demo.jar org.jfree.fx.demo.FXGraphics2DDemo1

The class does exist but is not included in any jar file by mvn package.

**Comment by jfree** [comment]
If you download the distribution from the FXGraphics2D home page (http://www.jfree.org/fxgraphics2d/) you will have a zip file containing the demo jar files.  Alternatively, you can build using the Ant script and you'll get the same result.

However, building with Maven will create only the runtime jar file...which I think is the problem that you are seeing here.  I don't plan to change that, but I'll make a note in the README.md to make it clearer.
